/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/get_request_history_file_list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Request History File List Route
         * @description Liste les fichiers dans le dossier platform/request_history
         *     Envoie la liste des noms de fichiers dans une seule réponse
         */
        get: operations["get_request_history_file_list_route_get_request_history_file_list_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/get_request_information": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Request Information Route
         * @description Récupère le contenu d'un fichier spécifique dans le dossier platform/request_history
         */
        get: operations["get_request_information_route_get_request_information_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/get_ndjson_snippets_file_list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ndjson Snippets File List
         * @description Liste les fichiers dans le dossier platform/ndjson_snippets
         *     Envoie la liste des noms de fichiers dans une seule réponse
         */
        get: operations["get_ndjson_snippets_file_list_get_ndjson_snippets_file_list_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CostInformations */
        CostInformations: {
            /**
             * Input Cost
             * @default 0
             */
            input_cost: number;
            /**
             * Output Cost
             * @default 0
             */
            output_cost: number;
            /**
             * Reasoning Cost
             * @default 0
             */
            reasoning_cost: number;
            /**
             * Reasoning Percent
             * @default 0
             */
            reasoning_percent: number;
            /**
             * Total Cost
             * @default 0
             */
            total_cost: number;
        };
        /** FileInfo */
        FileInfo: {
            /** File Name */
            file_name: string;
            /** Request Name */
            request_name: string;
            /** Created At */
            created_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LLMResponse */
        LLMResponse: {
            /**
             * Model
             * @default
             */
            model: string;
            /**
             * Temperature
             * @default 0
             */
            temperature: number;
            /**
             * Service Tier
             * @default
             */
            service_tier: string;
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens: number;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens: number;
            /**
             * Reasoning Tokens
             * @default 0
             */
            reasoning_tokens: number;
        };
        /** RequestHistoryFileListResponse */
        RequestHistoryFileListResponse: {
            /** Files */
            files: components["schemas"]["FileInfo"][];
        };
        /** RequestInformations */
        RequestInformations: {
            /**
             * Is Valid
             * @default true
             */
            is_valid: boolean;
            /**
             * Validity Error
             * @default
             */
            validity_error: string;
            /**
             * Model
             * @default
             */
            model: string;
            /**
             * Prompt
             * @default
             */
            prompt: string;
            /**
             * Response Content
             * @default
             */
            response_content: string;
            llm_response: components["schemas"]["LLMResponse"];
            cost_info: components["schemas"]["CostInformations"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_request_history_file_list_route_get_request_history_file_list_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestHistoryFileListResponse"];
                };
            };
        };
    };
    get_request_information_route_get_request_information_get: {
        parameters: {
            query: {
                file_name: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestInformations"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ndjson_snippets_file_list_get_ndjson_snippets_file_list_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
